//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVan.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public int id { get; set; }
        public Nullable<int> id_dispatch { get; set; }
        public Nullable<int> id_department { get; set; }
        public Nullable<System.DateTime> assingtime { get; set; }
        public Nullable<System.DateTime> completiontime { get; set; }
        public Nullable<int> userid_command { get; set; }
        public Nullable<int> userid_follow { get; set; }
        public Nullable<int> userid_perform { get; set; }
        public string work_content { get; set; }
        public string result { get; set; }
        public string attach_file { get; set; }
    
        public virtual department department { get; set; }
        public virtual row row { get; set; }
    }
}
