//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVan.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat()
        {
            this.rows = new HashSet<row>();
        }
    
        public int id { get; set; }
        public Nullable<int> parentid { get; set; }
        public string title { get; set; }
        public string introduction { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<int> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<row> rows { get; set; }
    }
}
