//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVan.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CongVanEntities : DbContext
    {
        public CongVanEntities()
            : base("name=CongVanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<cat> cats { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<department_cat> department_cat { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<follow> follows { get; set; }
        public virtual DbSet<groups_user> groups_user { get; set; }
        public virtual DbSet<row> rows { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
