//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVan.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int userid { get; set; }
        public int iddepart { get; set; }
        public Nullable<byte> office { get; set; }
    
        public virtual department department { get; set; }
        public virtual user user { get; set; }
    }
}
