//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVan.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class follow
    {
        public int id { get; set; }
        public Nullable<int> id_dispatch { get; set; }
        public Nullable<int> id_department { get; set; }
        public string list_userid { get; set; }
        public string list_timeview { get; set; }
        public string list_hitstotal { get; set; }
    
        public virtual department department { get; set; }
        public virtual row row { get; set; }
    }
}
