//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongVan.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class row
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public row()
        {
            this.assignments = new HashSet<assignment>();
            this.follows = new HashSet<follow>();
        }
    
        public int id { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> idcat { get; set; }
        public Nullable<int> idtype { get; set; }
        public string title { get; set; }
        public string @abstract { get; set; }
        public string name_signer { get; set; }
        public string name_initial { get; set; }
        public Nullable<int> level_important { get; set; }
        public string number_dispatch { get; set; }
        public string number_text_come { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> publtime { get; set; }
        public Nullable<System.DateTime> date_iss { get; set; }
        public Nullable<System.DateTime> date_first { get; set; }
        public Nullable<System.DateTime> date_die { get; set; }
        public string from_org { get; set; }
        public string to_org { get; set; }
        public Nullable<int> dep_catid { get; set; }
        public Nullable<int> to_depid { get; set; }
        public string attach_file { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<System.DateTime> term_view { get; set; }
        public Nullable<byte> reply { get; set; }
        public string groups_view { get; set; }
        public Nullable<int> views { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignment> assignments { get; set; }
        public virtual cat cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<follow> follows { get; set; }
        public virtual type type1 { get; set; }
    }
}
